package xj.ericli.ssi.db.ibatis.dao;

import java.sql.SQLException;
import java.util.List;

import xj.ericli.ssi.db.ibatis.model.Dept;
import xj.ericli.ssi.db.ibatis.model.DeptExample;

public interface DeptDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table dept
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	void insert(Dept record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table dept
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int updateByPrimaryKey(Dept record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table dept
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int updateByPrimaryKeySelective(Dept record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table dept
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	List selectByExample(DeptExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table dept
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	Dept selectByPrimaryKey(Integer deptid) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table dept
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int deleteByExample(DeptExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table dept
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int deleteByPrimaryKey(Integer deptid) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table dept
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int countByExample(DeptExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table dept
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int updateByExampleSelective(Dept record, DeptExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table dept
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int updateByExample(Dept record, DeptExample example) throws SQLException;
}