package xj.ericli.ssi.db.ibatis.dao;

import java.sql.SQLException;
import java.util.List;

import xj.ericli.ssi.db.ibatis.model.Staff;
import xj.ericli.ssi.db.ibatis.model.StaffExample;

public interface StaffDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	void insert(Staff record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int updateByPrimaryKey(Staff record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int updateByPrimaryKeySelective(Staff record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	List selectByExample(StaffExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	Staff selectByPrimaryKey(Integer staffId) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int deleteByExample(StaffExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int deleteByPrimaryKey(Integer staffId) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int countByExample(StaffExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int updateByExampleSelective(Staff record, StaffExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	int updateByExample(Staff record, StaffExample example) throws SQLException;
}