package xj.ericli.ssi.db.ibatis.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;

import xj.ericli.ssi.db.ibatis.model.Staff;
import xj.ericli.ssi.db.ibatis.model.StaffExample;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;

public class StaffDAOImpl implements StaffDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public StaffDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public void setSqlMapClient(SqlMapClient sqlMapClient) {
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public SqlMapClient getSqlMapClient() {
		return sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public void insert(Staff record) throws SQLException {
		sqlMapClient.insert("staff.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int updateByPrimaryKey(Staff record) throws SQLException {
		int rows = sqlMapClient.update("staff.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int updateByPrimaryKeySelective(Staff record) throws SQLException {
		int rows = sqlMapClient.update("staff.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public List selectByExample(StaffExample example) throws SQLException {
		List list = sqlMapClient.queryForList("staff.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public Staff selectByPrimaryKey(Integer staffId) throws SQLException {
		Staff key = new Staff();
		key.setStaffId(staffId);
		Staff record = (Staff) sqlMapClient.queryForObject("staff.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int deleteByExample(StaffExample example) throws SQLException {
		int rows = sqlMapClient.delete("staff.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int deleteByPrimaryKey(Integer staffId) throws SQLException {
		Staff key = new Staff();
		key.setStaffId(staffId);
		int rows = sqlMapClient.delete("staff.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int countByExample(StaffExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject("staff.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int updateByExampleSelective(Staff record, StaffExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("staff.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int updateByExample(Staff record, StaffExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("staff.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table staff
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private static class UpdateByExampleParms extends StaffExample {
		private Object record;

		public UpdateByExampleParms(Object record, StaffExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}