package xj.ericli.ssi.db.ibatis.dao;

import java.sql.SQLException;
import java.util.List;

import xj.ericli.ssi.db.ibatis.model.TUser;
import xj.ericli.ssi.db.ibatis.model.TUserExample;

import com.ibatis.sqlmap.client.SqlMapClient;

public class TUserDAOImpl implements TUserDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public TUserDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public void setSqlMapClient(SqlMapClient sqlMapClient) {
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public SqlMapClient getSqlMapClient() {
		return sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public Integer insert(TUser record) throws SQLException {
		Object newKey = sqlMapClient.insert("t_user.abatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int updateByPrimaryKey(TUser record) throws SQLException {
		int rows = sqlMapClient.update("t_user.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int updateByPrimaryKeySelective(TUser record) throws SQLException {
		int rows = sqlMapClient.update("t_user.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public List selectByExample(TUserExample example) throws SQLException {
		List list = sqlMapClient.queryForList("t_user.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public TUser selectByPrimaryKey(Integer id) throws SQLException {
		TUser key = new TUser();
		key.setId(id);
		TUser record = (TUser) sqlMapClient.queryForObject("t_user.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int deleteByExample(TUserExample example) throws SQLException {
		int rows = sqlMapClient.delete("t_user.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		TUser key = new TUser();
		key.setId(id);
		int rows = sqlMapClient.delete("t_user.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int countByExample(TUserExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject("t_user.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int updateByExampleSelective(TUser record, TUserExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("t_user.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public int updateByExample(TUser record, TUserExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("t_user.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_user
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private static class UpdateByExampleParms extends TUserExample {
		private Object record;

		public UpdateByExampleParms(Object record, TUserExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}