package xj.ericli.ssi.db.ibatis.model;

public class Dept {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column dept.deptId
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private Integer deptid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column dept.deptName
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private String deptname;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column dept.deptId
	 * @return  the value of dept.deptId
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public Integer getDeptid() {
		return deptid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column dept.deptId
	 * @param deptid  the value for dept.deptId
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column dept.deptName
	 * @return  the value of dept.deptName
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public String getDeptname() {
		return deptname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column dept.deptName
	 * @param deptname  the value for dept.deptName
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}
}