package xj.ericli.ssi.db.ibatis.model;

public class Staff {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column staff.STAFF_ID
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private Integer staffId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column staff.DEPT_ID
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private Integer deptId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column staff.STAFF_NAME
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private String staffName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column staff.CARD_ID
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private String cardId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column staff.STAFF_ID
	 * @return  the value of staff.STAFF_ID
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public Integer getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column staff.STAFF_ID
	 * @param staffId  the value for staff.STAFF_ID
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column staff.DEPT_ID
	 * @return  the value of staff.DEPT_ID
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column staff.DEPT_ID
	 * @param deptId  the value for staff.DEPT_ID
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column staff.STAFF_NAME
	 * @return  the value of staff.STAFF_NAME
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public String getStaffName() {
		return staffName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column staff.STAFF_NAME
	 * @param staffName  the value for staff.STAFF_NAME
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column staff.CARD_ID
	 * @return  the value of staff.CARD_ID
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public String getCardId() {
		return cardId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column staff.CARD_ID
	 * @param cardId  the value for staff.CARD_ID
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public void setCardId(String cardId) {
		this.cardId = cardId;
	}
}