package xj.ericli.ssi.db.ibatis.model;

public class TUser {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_user.ID
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_user.USERNAME
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private String username;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_user.ADDRESS
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	private String address;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_user.ID
	 * @return  the value of t_user.ID
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_user.ID
	 * @param id  the value for t_user.ID
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_user.USERNAME
	 * @return  the value of t_user.USERNAME
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_user.USERNAME
	 * @param username  the value for t_user.USERNAME
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_user.ADDRESS
	 * @return  the value of t_user.ADDRESS
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_user.ADDRESS
	 * @param address  the value for t_user.ADDRESS
	 * @abatorgenerated  Fri Dec 10 14:27:45 CST 2010
	 */
	public void setAddress(String address) {
		this.address = address;
	}
}